fitur_pink/urls.py
from django.urls import path
from . import views

appname: 'fitur_pink'

urlpatterns = [
    path('daftar_atlet/', views.daftar_atlet, name='daftar_atlet'),
    path('latih_atlet/', views.latih_atlet, name='latih_atlet'),
    path('list_atlet/', views.list_atlet, name='list_atlet'),
    path('list_partai_kompetisi/', views.list_partai_kompetisi, name='list_partai_kompetisi'),
    path('list_hasil_pertandingan/<str:jenis_partai>/<str:nama_event>/<int:tahun>/', views.list_hasil_pertandingan, name='list_hasil_pertandingan'),
]

fitur_putih/urls.py
from django.urls import path
from fitur_putih.views import *

app_name = 'fitur_putih'

urlpatterns = [
    path('login', login_member, name='login'),
    path('register/atlet', register_atlet, name='register_atlet'),
    path('register/pelatih', register_pelatih, name='register_pelatih'),
    path('register/umpire', register_umpire, name='register_umpire'),
    path('register', register, name='register'),
    path('logout', logout_user, name='logout'),
    path('', landing_page, name='landing_page'),
    path('dashboard/atlet', dashboard_atlet, name='dashboard_atlet'),
    path('dashboard/pelatih', dashboard_pelatih, name='dashboard_pelatih'),
    path('dashboard/umpire', dashboard_umpire, name='dashboard_umpire'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('example-app/', include('example_app.urls')),
    path('ungu/', include('fitur_ungu.urls')),
    path('', include('fitur_putih.urls')),
    path('hijau/', include('fitur_hijau.urls')),
    path('pink/', include('fitur_pink.urls')),
]

fitur_putih/views.py
from django.shortcuts import render
from django.http import HttpResponse
from fitur_putih.auth import authenticate, login, logout
import uuid
import psycopg2.extras
import psycopg2
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from fitur_putih.auth import login_required
from fitur_putih.auth import get_role_with_id
from datetime import date
from datetime import datetime


conn = psycopg2.connect(
    database = settings.DATABASE_NAME,
    user = settings.DATABASE_USER,
    password = settings.DATABASE_PASSWORD,
    host = settings.DATABASE_HOST,
    port = settings.DATABASE_PORT,
)
curr = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

# Create your views here.


def generate_error_message(exception):
    msg = str(exception)
    msg = msg[:msg.index('CONTEXT')-1]
    return msg

def login_member(request):
    if request.method == "GET":
        return render(request, "login.html")
    nama = request.POST["nama"]
    email = request.POST["email"]
    member = authenticate(nama = nama, email = email)
    if member == None:
        messages.error(request, "Email atau nama salah")
        return render(request, "login.html")
    return login(member['id'])
    

def register(request):
    return render(request, 'register.html')

def register_atlet(request):
    if request.method == "GET":
        return render(request, "register_atlet.html")
    
    id = generate_id()
    nama = request.POST['nama']
    email = request.POST['email']
    tgl_lahir = change_date_format(request.POST['tgl_lahir'])
    negara_asal = request.POST['negara']
    play_right = request.POST.get('kanan', None) != None
    height = request.POST['tinggi_badan']
    jenis_kelamin = request.POST.get('laki_laki', None) != None
        
    try:
        register_member(id, nama, email)
        insert_atlet = f"INSERT INTO ATLET VALUES(\'{id}\', \'{tgl_lahir}\', \'{negara_asal}\', \'{play_right}\', {height}, null, \'{jenis_kelamin}\')"
        curr.execute(insert_atlet)
        conn.commit()
    except Exception as e:
        error_msg = generate_error_message(e)
        messages.error(request, generate_error_message(e))
        conn.rollback()
        return render(request, "register_atlet.html")
    return HttpResponseRedirect(reverse("fitur_putih:login"))



def register_pelatih(request):
    if request.method == "GET":
        return render(request, "register_pelatih.html")
    
    id = generate_id()
    nama = request.POST['nama']
    email = request.POST['email']
    tgl_mulai = request.POST['tgl_mulai']
    tunggal_putra = request.POST.get('tunggal_putra', None)
    tunggal_putri = request.POST.get('tunggal_putri', None)
    ganda_putra = request.POST.get('ganda_putra', None)
    ganda_putri = request.POST.get('ganda_putri', None)
    ganda_campuran = request.POST.get('ganda_campuran', None)

    try:
        register_member(id, nama, email)
        insert_pelatih = f"INSERT INTO PELATIH VALUES(\'{id}\', \'{tgl_mulai}\')"
        curr.execute(insert_pelatih)
        if tunggal_putra != None:
            insert_pelatih_spesialisasi(id, "Tunggal Putra")
        if tunggal_putri != None:
            insert_pelatih_spesialisasi(id, "Tunggal Putri")
        if ganda_putra != None:
            insert_pelatih_spesialisasi(id, "Ganda Putra")
        if ganda_putri != None:
            insert_pelatih_spesialisasi(id, "Ganda Putri")
        if ganda_campuran != None:
            insert_pelatih_spesialisasi(id, "Ganda Campuran")
        conn.commit()
    except Exception as e:
        messages.error(request, generate_error_message(e))
        conn.rollback()
        return render(request, "register_pelatih.html")
    
    return HttpResponseRedirect(reverse("fitur_putih:login"))

def register_umpire(request):
    if request.method == "GET":
        return render(request, "register_umpire.html")
    id = generate_id()
    nama = request.POST['nama']
    email = request.POST['email']
    negara = request.POST['negara']
    
    try:
        register_member(id, nama, email)
        insert_umpire = f"INSERT INTO UMPIRE VALUES(\'{id}\', \'{negara}\')"
        curr.execute(insert_umpire)
        conn.commit()
    except Exception as e:
        messages.error(request, generate_error_message(e))
        conn.rollback()
        return render(request, "register_umpire.html")
    
    return HttpResponseRedirect(reverse("fitur_putih:login"))

    
def generate_id():
    id = str(uuid.uuid4())
    while is_exist_id(id):
        id = str(uuid.uuid4())
    return id
        
def is_exist_id(id):
    query = f'SELECT id FROM MEMBER WHERE MEMBER.id = \'{id}\''
    curr.execute(query)
    lst = curr.fetchall()
    return len(lst) > 0
    
def change_date_format(tgl):
    """
    Change date format to YYYY-mm-dd
    return date in string
    """
    return f'{tgl[6:]}-{tgl[3:5]}-{tgl[0:2]}'

def register_member(id, nama, email):
    insert_member = f"INSERT INTO MEMBER VALUES(\'{id}\', \'{nama}\', \'{email}\')"
    curr.execute(insert_member)

def insert_pelatih_spesialisasi(id, sp):
    query = f'SELECT id FROM SPESIALISASI WHERE spesialisasi = \'{sp}\''
    curr.execute(query)
    lst = curr.fetchall()
    id_sp = dict(lst[0])['id']
    query = f'INSERT INTO PELATIH_SPESIALISASI VALUES(\'{id}\', \'{id_sp}\')'
    curr.execute(query)

def logout_user(request):
    return logout()

def landing_page(request):
    return render(request, 'landing_page.html')


@login_required(role="PELATIH")
def dashboard_pelatih(request):
    id = request.COOKIES['id']
    query = ("SELECT M.nama, M.email, P.tanggal_mulai, STRING_AGG(S.spesialisasi, \', \') AS spesialisasi "
            + "FROM MEMBER M "
            + f"JOIN PELATIH P ON P.id = \'{id}\' AND P.id = M.id "
            + "JOIN PELATIH_SPESIALISASI PS ON PS.id_pelatih = P.id "
            + "JOIN SPESIALISASI S ON PS.id_spesialisasi = S.id "
            + "GROUP BY P.id, M.id")
    curr.execute(query)
    lst = curr.fetchall()
    pelatih = dict(lst[0])
    context = {
        'pelatih':pelatih
    }
    return render(request, 'dashboard_pelatih.html', context)

@login_required(role="ATLET")
def dashboard_atlet(request):
    id = request.COOKIES.get('id', None)
    query = ("SELECT M.nama, M.email, A.negara_asal, A.tgl_lahir, A.play_right, A.height, A.world_rank, A.jenis_kelamin, STRING_AGG(P.nama, \', \') AS pelatih "
            + "FROM MEMBER M "
            + f"JOIN ATLET A ON A.id = \'{id}\' AND A.id = M.id "
            + "JOIN ATLET_PELATIH AP ON AP.id_atlet = A.id "
            + "JOIN (SELECT PEL.id, MEM.nama FROM PELATIH PEL JOIN MEMBER MEM ON PEL.id = MEM.id) P ON AP.id_pelatih = P.id "
            + "GROUP BY M.id, A.id")
    curr.execute(query)
    lst = curr.fetchall()
    atlet = dict(lst[0])
    atlet['total_point'] = get_total_point_atlet(id)
    context = {
        'atlet':atlet
    }
    return render(request, "dashboard_atlet.html", context)

def get_total_point_atlet(id):
    query = f"SELECT * FROM POINT_HISTORY WHERE id_atlet = \'{id}\'"
    curr.execute(query)
    lst = curr.fetchall()
    if len(lst) == 0:
        return 0
    change_format(lst)
    return create_total_point(lst)

def create_total_point(lst):
    lst = sorted(lst, key= lambda x: (x['tahun'], x['bulan'], x['minggu_ke']), reverse=True)
    total_point = 0
    for elm in lst[:52]:
        total_point += elm['total_point']
    return total_point

@login_required(role="UMPIRE")
def dashboard_umpire(request):
    id = request.COOKIES['id']
    query = f"SELECT M.nama, M.email, U.negara FROM MEMBER AS M, UMPIRE AS U WHERE U.id = \'{id}\' AND U.id = M.id"
    curr.execute(query)
    lst = curr.fetchall()
    umpire = dict(lst[0])
    context = {
        'umpire':umpire
    }
    return render(request, 'dashboard_umpire.html', context)

def change_format(lst):
    for i in range(len(lst)):
        lst[i] = dict(lst[i])
        change_month(lst[i])

def change_month(param):
    param['bulan'] = datetime.strptime(param['bulan'], '%B').month
        
        

fitur_putih/templates/dashboard_atlet.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% include 'navbar_atlet.html' %}

    <title>Dashboard Atlet</title>
    <style>
        html, body {
            height: 100%;
        }
        .h-100 .h-custom {
            width: 100%;
            height: 100%;
            display: table;
            text-align: center;
        }
    </style>

    {% endblock meta %}
    {% block content %}
    
    <section class="h-100 h-custom" style="background-color: #8fc4b7; height: 100vh;">
        <div class="container py-5 h-100" style="height: 100vh;">
            <div class="row d-flex justify-content-center align-items-center h-100" style="height: 100vh;">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://lh3.googleusercontent.com/upSMtCcURxcLw0ZS8g92NbFH-znB32z9Wo9mS3xtBEawGjLnrT83fS7KjLqYkLWCkcIHXS3MiP7JwgDqKxW5zt-nxYhJddIp3HMKJo5w3w"
                        class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                        alt="Sample photo">
                        <div class="card-body p-4 p-md-5">
                            <center>
                                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Hi There, Atlet {{atlet.nama}}</h3>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Negara : {{atlet.negara_asal}}</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Email : {{atlet.email}}</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Tanggal Lahir : {{atlet.tgl_lahir}}</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Play : {% if atlet.play_right %} Tangan Kanan {% else %} Tangan Kiri {% endif %}</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Tinggi Badan : {{atlet.height}}cm</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Jenis Kelamin : {% if atlet.jenis_kelamin %} Laki-laki {% else %} Perempuan {% endif %}</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Pelatih : {{atlet.pelatih}}</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Status : {% if atlet.world_rank %} Qualified {% else %} Not Qualified {% endif %}</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">World Rank : {% if atlet.world_rank %} {{atlet.world_rank}} {% else %} - {% endif %}</h5>
                                <h5 class="mb-3 pb-1 pb-md-0 mb-md-4 px-md-1">Total Poin : {{atlet.total_point}}</h5>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

fitur_putih/templates/dashboard_pelatih.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% include 'navbar_pelatih.html' %}

    <title>Dashboard Pelatih</title>
    <style>
        html, body {
            height: 100%;
        }
        .h-100 .h-custom {
            width: 100%;
            height: 100%;
            display: table;
            text-align: center;
        }
    </style>

{% endblock meta %}
{% block content %}
    <section class="h-100 h-custom" style="background-color: #8fc4b7; height: 100vh;">
        <div class="container py-5 h-100" style="height: 100vh;">
            <div class="row d-flex justify-content-center align-items-center h-100" style="height: 100vh;">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://lh3.googleusercontent.com/upSMtCcURxcLw0ZS8g92NbFH-znB32z9Wo9mS3xtBEawGjLnrT83fS7KjLqYkLWCkcIHXS3MiP7JwgDqKxW5zt-nxYhJddIp3HMKJo5w3w"
                        class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                        alt="Sample photo">
                        <div class="card-body p-4 p-md-5">
                            <center>
                                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Hi There, Pelatih {{pelatih.nama}}</h3>
                                <h4 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Email : {{pelatih.email}}</h4>
                                <h4 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Spesialisasi Kategori : {{pelatih.spesialisasi}}</h4>
                                <h4 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Tanggal Mulai : {{pelatih.tanggal_mulai}}</h4>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

fitur_putih/templates/dashboard_umpire.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% include 'navbar_umpire.html' %}
    <title>Dashboard Umpire</title>

    <style>
        html, body {
            height: 100%;
        }
        .h-100 .h-custom {
            width: 100%;
            height: 100%;
            display: table;
            text-align: center;
        }
    </style>
    {% endblock meta %}
    {% block content %}
    
    <section class="h-100 h-custom" style="background-color: #8fc4b7; height: 100vh;">
        <div class="container py-5 h-100" style="height: 100vh;">
            <div class="row d-flex justify-content-center align-items-center h-100" style="height: 100vh;">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://lh3.googleusercontent.com/upSMtCcURxcLw0ZS8g92NbFH-znB32z9Wo9mS3xtBEawGjLnrT83fS7KjLqYkLWCkcIHXS3MiP7JwgDqKxW5zt-nxYhJddIp3HMKJo5w3w"
                        class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                        alt="Sample photo">
                        <div class="card-body p-4 p-md-5">
                            <center>
                                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Hi There, Umpire {{umpire.nama}}</h3>
                                <h4 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Negara : {{umpire.negara}}</h4>
                                <h4 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Email : {{umpire.email}}</h4>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

fitur_putih/templates/landing_page.html
{% extends 'base.html' %}

{% block meta %}
{% load static %}
    <title>Babadu</title>
{% endblock meta %}
{% block content %}
    <style>
        html, body {
            height: 100%;
        }
        .h-100 .h-custom {
            width: 100%;
            height: 100%;
            display: table;
            text-align: center;
        }
    </style>
    <section class="h-100 h-custom" style="background-color: #8fc4b7; height: 100vh;">
        <div class="container py-5 h-100" style="height: 100vh;">
            <div class="row d-flex justify-content-center align-items-center h-100" style="height: 100vh;">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://lh3.googleusercontent.com/upSMtCcURxcLw0ZS8g92NbFH-znB32z9Wo9mS3xtBEawGjLnrT83fS7KjLqYkLWCkcIHXS3MiP7JwgDqKxW5zt-nxYhJddIp3HMKJo5w3w"
                        class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                        alt="Sample photo">
                        <div class="card-body p-4 p-md-5">
                            <center>
                                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">BABADU - E13</h3>
                            </center>
                                <center>
                                    <a href="{% url 'fitur_putih:login' %}"><button class="btn btn-success btn-lg mb-1">Login</button></a>
                                    <div></div>
                                    <a href="{% url 'fitur_putih:register' %}"><button class="btn btn-success btn-lg mb-1">Register</button></a>
                                </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

fitur_putih/templates/login.html
{% extends 'base.html' %}

{% block meta %}
{% load static %}
    <title>Login</title>
{% endblock meta %}
{% block content %}
    <style>
        html, body {
            height: 100%;
        }
        .h-100 .h-custom {
            width: 100%;
            height: 100%;
            display: table;
            text-align: center;
        }
    </style>
    <section class="h-100 h-custom" style="background-color: #8fc4b7; height: 100vh;">
        <div class="container py-5 h-100" style="height: 100vh;">
            <div class="row d-flex justify-content-center align-items-center h-100" style="height: 100vh;">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://lh3.googleusercontent.com/upSMtCcURxcLw0ZS8g92NbFH-znB32z9Wo9mS3xtBEawGjLnrT83fS7KjLqYkLWCkcIHXS3MiP7JwgDqKxW5zt-nxYhJddIp3HMKJo5w3w"
                        class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                        alt="Sample photo">
                        <div class="card-body p-4 p-md-5">
                            <center>
                                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Welcome To Babadu</h3>
                            </center>
                            <form class="px-md-2" method="POST">
                                {% csrf_token %}
                                <div class="form-outline mb-4">
                                    <input type="text" name="nama" class="form-control" placeholder="Nama"/>
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="email" class="form-control" placeholder="Email"/>
                                </div>
                                <center>
                                    <button type="submit" class="btn btn-success btn-lg mb-1">Login</button>
                                </center>
                            </form>
                        </div>
                        {% if messages %}
                            <ul>
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    
{% endblock content %}

fitur_putih/templates/register.html
{% extends 'base.html' %}

{% block meta %}
{% load static %}
    <title>Babadu | Register</title>
{% endblock meta %}
{% block content %}
    <style>
        html, body {
            height: 100%;
        }
        .h-100 .h-custom {
            width: 100%;
            height: 100%;
            display: table;
            text-align: center;
        }
    </style>
    <section class="h-100 h-custom" style="background-color: #8fc4b7; height: 100vh;">
        <div class="container py-5 h-100" style="height: 100vh;">
            <div class="row d-flex justify-content-center align-items-center h-100" style="height: 100vh;">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://lh3.googleusercontent.com/upSMtCcURxcLw0ZS8g92NbFH-znB32z9Wo9mS3xtBEawGjLnrT83fS7KjLqYkLWCkcIHXS3MiP7JwgDqKxW5zt-nxYhJddIp3HMKJo5w3w"
                        class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                        alt="Sample photo">
                        <div class="card-body p-4 p-md-5">
                            <center>
                                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Babadu | Register</h3>
                            </center>
                            <div class="row justify-content-center p-2">
                            <a href="{% url 'fitur_putih:register_atlet' %}"><button class="btn"> Atlet </button></a>
                            </div>
                            <div class="row justify-content-center p-2">
                            <a href="{% url 'fitur_putih:register_pelatih' %}"><button class="btn"> Pelatih </button></a>
                            </div>
                            <div class="row justify-content-center p-2">
                            <a href="{% url 'fitur_putih:register_umpire' %}"><button class="btn"> Umpire </button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

fitur_putih/templates/register_atlet.html
{% extends 'base.html' %}

{% block meta %}
{% load static %}
    <title>Register Atlet</title>
{% endblock meta %}
{% block content %}
    <style>
        html, body {
            height: 100%;
        }
        .h-100 .h-custom {
            width: 100%;
            height: 100%;
            display: table;
            text-align: center;
        }
    </style>
    <section class="h-100 h-custom" style="background-color: #8fc4b7; height: 100vh;">
        <div class="container py-5 h-100" style="height: 100vh;">
            <div class="row d-flex justify-content-center align-items-center h-100" style="height: 100vh;">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://lh3.googleusercontent.com/upSMtCcURxcLw0ZS8g92NbFH-znB32z9Wo9mS3xtBEawGjLnrT83fS7KjLqYkLWCkcIHXS3MiP7JwgDqKxW5zt-nxYhJddIp3HMKJo5w3w"
                        class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                        alt="Sample photo">
                        <div class="card-body p-4 p-md-5">
                            <center>
                                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Babadu | Register Atlet</h3>
                            </center>
                            <form class="px-md-2" method="POST">
                                {% csrf_token %}
                                <div class="form-outline mb-4">
                                    <input type="text" name="nama" class="form-control" placeholder="Nama"/>
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="email" class="form-control" placeholder="Email"/>
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="negara" class="form-control" placeholder="Negara"/>
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="tgl_lahir" class="form-control" placeholder="Tanggal Lahir (cth: 13-09-2002)"/>
                                </div>
                                <p>Play</p>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="kanan" id="kanan" checked>
                                    <label class="form-check-label" for="kanan">
                                      Tangan Kanan
                                    </label>
                                </div>
                                <div class="form-check pb-4">
                                    <input class="form-check-input" type="radio" name="kiri" id="kiri">
                                    <label class="form-check-label" for="kiri">
                                      Tangan Kiri
                                    </label>
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="tinggi_badan" class="form-control" placeholder="Tinggi Badan"/>
                                </div>
                                <p>Jenis Kelamin</p>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="laki_laki" id="laki-laki" checked>
                                    <label class="form-check-label" for="laki-laki">
                                      Laki-laki
                                    </label>
                                </div>
                                <div class="form-check pb-2">
                                    <input class="form-check-input" type="radio" name="perempuan" id="perempuan">
                                    <label class="form-check-label" for="perempuan">
                                      Wanita
                                    </label>
                                </div>
                                
                                <center>
                                    <button type="submit" class="btn btn-success btn-lg mb-1">Daftar</button>
                                </center>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% if messages %}
    {% for message in messages %}
    {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

    {% endfor %}

    {% endif %}
{% endblock content %}

fitur_putih/templates/register_umpire.html
{% extends 'base.html' %}

{% block meta %}
{% load static %}
    <title>Register Umpire</title>
{% endblock meta %}
{% block content %}
    <style>
        html, body {
            height: 100%;
        }
        .h-100 .h-custom {
            width: 100%;
            height: 100%;
            display: table;
            text-align: center;
        }
    </style>
    <section class="h-100 h-custom" style="background-color: #8fc4b7; height: 100vh;">
        <div class="container py-5 h-100" style="height: 100vh;">
            <div class="row d-flex justify-content-center align-items-center h-100" style="height: 100vh;">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img src="https://lh3.googleusercontent.com/upSMtCcURxcLw0ZS8g92NbFH-znB32z9Wo9mS3xtBEawGjLnrT83fS7KjLqYkLWCkcIHXS3MiP7JwgDqKxW5zt-nxYhJddIp3HMKJo5w3w"
                        class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                        alt="Sample photo">
                        <div class="card-body p-4 p-md-5">
                            <center>
                                <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Babadu | Register Umpire</h3>
                            </center>
                            <form class="px-md-2" method="POST">
                                {% csrf_token %}
                                <div class="form-outline mb-4">
                                    <input type="text" name="nama" class="form-control" placeholder="Nama">
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="email" class="form-control" placeholder="Email">
                                </div>
                                <div class="form-outline mb-4">
                                    <input type="text" name="negara" class="form-control" placeholder="Negara">
                                </div>
                                <center>
                                    <button type="submit" class="btn btn-success btn-lg mb-1">Register</button>
                                </center>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% if messages %}
    {% for message in messages %}
    {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

    {% endfor %}

    {% endif %}
{% endblock content %}