fitur_hijau/urls.py
from django.urls import path
from fitur_hijau.views import *

app_name = 'fitur_hijau'

urlpatterns = [
    path('ujiankualifikasi/umpire/create', ujian_kualifikasi_umpire_create, name='ujian_kualifikasi_umpire_create'),
    path('ujiankualifikasi/umpire/read', ujian_kualifikasi_umpire_read, name='ujian_kualifikasi_umpire_read'),
    path('ujiankualifikasi/question', ujian_kualifikasi_question, name='ujian_kualifikasi_question'),
    path('ujiankualifikasi/atlet', ujian_kualifikasi_atlet, name='ujian_kualifikasi_atlet'),
    path('ujiankualifikasi/riwayat/atlet', riwayat_kualifikasi_atlet, name='riwayat_kualifikasi_atlet'),
    path('ujiankualifikasi/riwayat/umpire', riwayat_kualifikasi_umpire, name='riwayat_kualifikasi_umpire'),
     path('ujiankualifikasi/question/kualifikasi', atlet_kualifikasi_question, name='atlet_kualifikasi_question'),

]

fitur_pink/urls.py
from django.urls import path
from . import views

appname: 'fitur_pink'

urlpatterns = [
    path('daftar_atlet/', views.daftar_atlet, name='daftar_atlet'),
    path('latih_atlet/', views.latih_atlet, name='latih_atlet'),
    path('list_atlet/', views.list_atlet, name='list_atlet'),
    path('list_partai_kompetisi/', views.list_partai_kompetisi, name='list_partai_kompetisi'),
    path('list_hasil_pertandingan/<str:jenis_partai>/<str:nama_event>/<int:tahun>/', views.list_hasil_pertandingan, name='list_hasil_pertandingan'),
]

fitur_putih/urls.py
from django.urls import path
from fitur_putih.views import *

app_name = 'fitur_putih'

urlpatterns = [
    path('login', login_member, name='login'),
    path('register/atlet', register_atlet, name='register_atlet'),
    path('register/pelatih', register_pelatih, name='register_pelatih'),
    path('register/umpire', register_umpire, name='register_umpire'),
    path('register', register, name='register'),
    path('logout', logout_user, name='logout'),
    path('', landing_page, name='landing_page'),
    path('dashboard/atlet', dashboard_atlet, name='dashboard_atlet'),
    path('dashboard/pelatih', dashboard_pelatih, name='dashboard_pelatih'),
    path('dashboard/umpire', dashboard_umpire, name='dashboard_umpire'),
]

fitur_ungu/urls.py
from django.urls import path
from fitur_ungu.views import *

app_name = 'fitur_ungu'

urlpatterns = [
    path('enrolled-event', enrolled_event, name='enrolled_event'),
    path('daftar-sponsor', daftar_sponsor, name='daftar_sponsor'),
    path('list-sponsor', list_sponsor, name='list_sponsor'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('example-app/', include('example_app.urls')),
    path('ungu/', include('fitur_ungu.urls')),
    path('', include('fitur_putih.urls')),
    path('hijau/', include('fitur_hijau.urls')),
    path('pink/', include('fitur_pink.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<style>
  .dropdown {
      position: relative;
      display: inline-block;
  }

  .dropdown-content {
      display: none;
      position: absolute;
      min-width: 160px;
      z-index: 1;
  }

  .dropdown-content a {
      color: black;
      padding: 12px 16px;
      text-decoration: none;
      display: block;
  }

  .dropdown:hover .dropdown-content {
      display: block;
  }
</style>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/navbar_atlet.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #8fc4b7;">
    <a class="navbar-brand" href="#" style="color: #FFFFFF;">Babadu</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fitur_putih:dashboard_atlet' %}" style="color: #FFFFFF;">Dashboard</a>
        </li>
        <div class="dropdown">
            <a class="nav-link" href="#" style="color: #FFFFFF;">Ujian Kualifikasi</a>
            <div class="dropdown-content">
                <a href="{% url 'fitur_hijau:ujian_kualifikasi_atlet' %}">List Ujian Kualifikasi</a>
                <a href="{% url 'fitur_hijau:riwayat_kualifikasi_atlet' %}">Riwayat Ujian Kualifikasi</a>
            </div>
        </div>
        <div class="dropdown">
            <a class="nav-link" href="#" style="color: #FFFFFF;">Event</a>
            <div class="dropdown-content">
                <a href="#">Daftar Event</a>
                <a href="{% url 'fitur_ungu:enrolled_event'%}">Enrolled Event</a>
            </div>
        </div>
        <div class="dropdown">
            <a class="nav-link" href="#" style="color: #FFFFFF;">Sponsor</a>
            <div class="dropdown-content">
                <a href="{% url 'fitur_ungu:daftar_sponsor'%}">Daftar Sponsor</a>
                <a href="{% url 'fitur_ungu:list_sponsor'%}">List Sponsor</a>
            </div>
        </div>
        <a class ="btn" href="{% url 'fitur_putih:logout' %}" type="submit">Logout</a>
    </div>
</nav>

templates/navbar_pelatih.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #8fc4b7;">
    <a class="navbar-brand" href="#" style="color: #FFFFFF;">Babadu</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'fitur_putih:dashboard_pelatih' %}" style="color: #FFFFFF;">Dashboard</a>
        </li>
        <div class="dropdown">
            <a class="nav-link" href="#" style="color: #FFFFFF;">Latih Atlet</a>
            <div class="dropdown-content">
                <a href="{% url 'latih_atlet' %}">Create Latih Atlet</a>
                <a href="{% url 'list_atlet' %}">List Atlet Dilatih</a>
            </div>
        </div>
        <a class ="btn" href="{% url 'fitur_putih:logout' %}" type="submit">Logout</a>
    </div>
</nav>

templates/navbar_umpire.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #8fc4b7;">
  <a class="navbar-brand" href="#" style="color: #FFFFFF;">Babadu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'fitur_putih:dashboard_umpire' %}" style="color: #FFFFFF;">Dashboard</a>
      </li>
      <div class="dropdown">
          <a class="nav-link" href="#" style="color: #FFFFFF;">Atlet</a>
          <div class="dropdown-content">
              <a href="{% url 'daftar_atlet' %}">Daftar Atlet</a>
          </div>
      </div>
      <div class="dropdown">
          <a class="nav-link" href="#" style="color: #FFFFFF;">Ujian Kualifikasi</a>
          <div class="dropdown-content">
              <a href="{% url 'fitur_hijau:ujian_kualifikasi_umpire_create' %}">Buat Ujian Kualifikasi</a>
              <a href="{% url 'fitur_hijau:ujian_kualifikasi_umpire_read' %}">List Ujian Kualifikasi</a>
              <a href="{% url 'fitur_hijau:riwayat_kualifikasi_umpire' %}">Riwayat Ujian Kualifikasi</a>
          </div>
      </div> 
      <div class="dropdown">
          <a class="nav-link" href="#" style="color: #FFFFFF;">Event</a>
          <div class="dropdown-content">
              <a href="{% url 'list_partai_kompetisi' %}">List Partai Kompetisi</a>
          </div>
      </div>
      <a class ="btn" href="{% url 'fitur_putih:logout' %}" type="submit">Logout</a>
  </div>
</nav>